name: Build

on: [push]

env:
  BUCKET_NAME: wallet-info-web
  AWS_REGION: us-west-2
  AWS_ROLE: arn:aws:iam::372622705083:role/s3-deploy
  AWS_SESSION_NAME: githubrolesession

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  build:
    environment: develop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        role-session-name: ${{ env.AWS_SESSION_NAME }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Upload to S3 bucket
      run: aws s3 sync ./dist/ s3://{{ env.BUCKET_NAME }} --delete
